# [bridge.core]

service_providers:
  # Register all your service providers here.
  - bridge.http.HttpServiceProvider
  - bridge.view.ViewServiceProvider
  - bridge.tether.TetherServiceProvider
  - bridge.events.EventsServiceProvider
  - bridge.database.DatabaseServiceProvider
  - services.MainServiceProvider
  - services.HttpExceptionsServiceProvider
  - services.CommandsServiceProvider
